spring:
  datasource:
    url: jdbc:sqlserver://${mssql_url:localhost:1433};databaseName=${mssql_db:gbank}
    username: ${mssql_user:sa}
    password: ${mssql_pass:P@ssw0rd}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 2011
  servlet:
    context-path: /${spring.application.name}/v${spring.application.version}


logging:
  level:
    customer-service: DEBUG
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.hibernate:
#     SQL: DEBUG
#     type: TRACE


