spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=loan
    username: sa
    password: P@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    homePageUrl: "http://${eureka.hostname}:2099/template/" # update port, replace 'template'

server:
  port: 2099
  servlet:
    context-path: /template

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate:
     SQL: DEBUG
     type: TRACE


