spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=gbank
    username: sa
    password: P@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 2011
  servlet:
    context-path: /customer/v${spring.application.version}


logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate:
     SQL: DEBUG
     type: TRACE


