spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=gbank
    username: sa
    password: P@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    homePageUrl: "http://${eureka.hostname}:2099/template/" # update port, replace 'template'

server:
  port: 2011
  servlet:
    context-path: /customer/v1.0



logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate:
     SQL: DEBUG
     type: TRACE


